FROM python:3.11.9-slim

WORKDIR /usr/src/app
COPY requirements.txt .

RUN apt update -y
RUN apt install build-essential libpq-dev -y
RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

COPY . .
ENV DB_USERNAME=myuser
ENV DB_PASSWORD=mypassword
ENV DB_HOST=127.0.0.1
ENV DB_PORT=5433
ENV DB_NAME=mydatabase

# Expose the port the app runs on
EXPOSE 5153

CMD ["python3", "app.py"]
